-- 후보 목록은 처음 만들 때만 채워요. 재실행해도 DB에서 수정하거나 삭제한 후보를 되돌리지 않아요.
-- 테이블 생성과 초기 적재를 한 문장으로 실행해 둘 중 하나만 반영되지 않게 해요.
CREATE TABLE IF NOT EXISTS chat_alias_players (
    english_name VARCHAR(255) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
    korean_name VARCHAR(255) NOT NULL,
    -- 배정된 닉네임의 최대 길이 80자에서 밑줄과 4자리 코드 길이를 빼요.
    short_en VARCHAR(75) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    short_ko VARCHAR(75) COLLATE utf8mb4_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
AS
SELECT 'Johan Cruyff' AS english_name, '요한 크루이프' AS korean_name, 'Cruyff' AS short_en, '크루이프' AS short_ko
UNION ALL SELECT 'Eusébio', '에우제비우', 'Eusebio', '에우제비우'
UNION ALL SELECT 'Roberto Baggio', '로베르토 바조', 'Baggio', '바조'
UNION ALL SELECT 'Rivaldo', '히바우두', 'Rivaldo', '히바우두'
UNION ALL SELECT 'Claude Makélélé', '클로드 마켈렐레', 'Makelele', '마켈렐레'
UNION ALL SELECT 'Fabio Cannavaro', '파비오 칸나바로', 'Cannavaro', '칸나바로'
UNION ALL SELECT 'Raúl González', '라울', 'Raul', '라울'
UNION ALL SELECT 'Steven Gerrard', '스티븐 제라드', 'Gerrard', '제라드'
UNION ALL SELECT 'Frank Lampard', '프랭크 램파드', 'Lampard', '램파드'
UNION ALL SELECT 'Alessandro Del Piero', '알레산드로 델피에로', 'DelPiero', '델피에로'
UNION ALL SELECT 'Brian Laudrup', '브리안 라우드루프', 'Laudrup', '라우드루프'
UNION ALL SELECT 'Carlos Valderrama', '카를로스 발데라마', 'Valderrama', '발데라마'
UNION ALL SELECT 'Ian Wright', '이언 라이트', 'Wright', '라이트'
UNION ALL SELECT 'Didier Drogba', '디디에 드로그바', 'Drogba', '드로그바'
UNION ALL SELECT 'Dennis Bergkamp', '데니스 베르캄프', 'Bergkamp', '베르캄프'
UNION ALL SELECT 'Davor Šuker', '다보르 슈케르', 'Suker', '슈케르'
UNION ALL SELECT 'Sócrates', '소크라테스', 'Socrates', '소크라테스'
UNION ALL SELECT 'David Seaman', '데이비드 시먼', 'Seaman', '시먼'
UNION ALL SELECT 'Emmanuel Petit', '에마뉘엘 프티', 'Petit', '프티'
UNION ALL SELECT 'Gary Lineker', '게리 리네커', 'Lineker', '리네커'
UNION ALL SELECT 'Roberto Carlos', '호베르투 카를루스', 'RobertoCarlos', '카를루스'
UNION ALL SELECT 'Gianluca Zambrotta', '잔루카 잠브로타', 'Zambrotta', '잠브로타'
UNION ALL SELECT 'Gianfranco Zola', '잔프랑코 졸라', 'Zola', '졸라'
UNION ALL SELECT 'Hernán Crespo', '에르난 크레스포', 'Crespo', '크레스포'
UNION ALL SELECT 'Alexi Lalas', '알렉시 랄라스', 'Lalas', '랄라스'
UNION ALL SELECT 'Jens Lehmann', '옌스 레만', 'Lehmann', '레만'
UNION ALL SELECT 'Oliver Bierhoff', '올리버 비어호프', 'Bierhoff', '비어호프'
UNION ALL SELECT 'Robbie Fowler', '로비 파울러', 'Fowler', '파울러'
UNION ALL SELECT 'Ole Gunnar Solskjær', '올레 군나르 솔샤르', 'Solskjaer', '솔샤르'
UNION ALL SELECT 'Teddy Sheringham', '테디 셰링엄', 'Sheringham', '셰링엄'
UNION ALL SELECT 'Zinedine Zidane', '지네딘 지단', 'Zidane', '지단'
UNION ALL SELECT 'Garrincha', '가린샤', 'Garrincha', '가린샤'
UNION ALL SELECT 'Ian Rush', '이언 러시', 'Rush', '러시'
UNION ALL SELECT 'Paulo Futre', '파울루 푸트리', 'Futre', '푸트리'
UNION ALL SELECT 'Ronaldinho', '호나우지뉴', 'Ronaldinho', '호나우지뉴'
UNION ALL SELECT 'Andrea Pirlo', '안드레아 피를로', 'Pirlo', '피를로'
UNION ALL SELECT 'Kaká', '카카', 'Kaka', '카카'
UNION ALL SELECT 'Hugo Sánchez', '우고 산체스', 'Sanchez', '산체스'
UNION ALL SELECT 'Patrick Vieira', '파트리크 비에이라', 'Vieira', '비에이라'
UNION ALL SELECT 'Michael Owen', '마이클 오언', 'Owen', '오언'
UNION ALL SELECT 'Carlos Alberto Torres', '카를루스 아우베르투', 'CarlosAlberto', '아우베르투'
UNION ALL SELECT 'Clarence Seedorf', '클라렌스 세도르프', 'Seedorf', '세도르프'
UNION ALL SELECT 'Rio Ferdinand', '리오 퍼디난드', 'Ferdinand', '퍼디난드'
UNION ALL SELECT 'Ronald Koeman', '로날트 쿠만', 'Koeman', '쿠만'
UNION ALL SELECT 'Peter Schmeichel', '페터 슈마이켈', 'Schmeichel', '슈마이켈'
UNION ALL SELECT 'Laurent Blanc', '로랑 블랑', 'Blanc', '블랑'
UNION ALL SELECT 'Gennaro Gattuso', '젠나로 가투소', 'Gattuso', '가투소'
UNION ALL SELECT 'David Trezeguet', '다비드 트레제게', 'Trezeguet', '트레제게'
UNION ALL SELECT 'Juan Sebastián Verón', '후안 세바스티안 베론', 'Veron', '베론'
UNION ALL SELECT 'Michael Essien', '마이클 에시앙', 'Essien', '에시앙'
UNION ALL SELECT 'Michael Laudrup', '미카엘 라우드루프', 'Laudrup', '라우드루프'
UNION ALL SELECT 'Pep Guardiola', '펩 과르디올라', 'Guardiola', '과르디올라'
UNION ALL SELECT 'Sol Campbell', '솔 캠벨', 'Campbell', '캠벨'
UNION ALL SELECT 'Gary Neville', '게리 네빌', 'Neville', '네빌'
UNION ALL SELECT 'Jay-Jay Okocha', '제이제이 오코차', 'Okocha', '오코차'
UNION ALL SELECT 'Jamie Carragher', '제이미 캐러거', 'Carragher', '캐러거'
UNION ALL SELECT 'Frank de Boer', '프랑크 더부르', 'DeBoer', '더부르'
UNION ALL SELECT 'John Barnes', '존 반스', 'Barnes', '반스'
UNION ALL SELECT 'Hidetoshi Nakata', '나카타 히데토시', 'Nakata', '나카타'
UNION ALL SELECT 'Ferenc Puskás', '페렌츠 푸스카스', 'Puskas', '푸스카스'
UNION ALL SELECT 'Lev Yashin', '레프 야신', 'Yashin', '야신'
UNION ALL SELECT 'Xavi Hernández', '차비', 'Xavi', '차비'
UNION ALL SELECT 'Frank Rijkaard', '프랑크 레이카르트', 'Rijkaard', '레이카르트'
UNION ALL SELECT 'Thierry Henry', '티에리 앙리', 'Henry', '앙리'
UNION ALL SELECT 'Eric Cantona', '에릭 칸토나', 'Cantona', '칸토나'
UNION ALL SELECT 'Pavel Nedvěd', '파벨 네드베드', 'Nedved', '네드베드'
UNION ALL SELECT 'Kenny Dalglish', '케니 달글리시', 'Dalglish', '달글리시'
UNION ALL SELECT 'Carles Puyol', '카를레스 푸욜', 'Puyol', '푸욜'
UNION ALL SELECT 'Philipp Lahm', '필립 람', 'Lahm', '람'
UNION ALL SELECT 'David Beckham', '데이비드 베컴', 'Beckham', '베컴'
UNION ALL SELECT 'Fernando Torres', '페르난도 토레스', 'Torres', '토레스'
UNION ALL SELECT 'Filippo Inzaghi', '필리포 인자기', 'Inzaghi', '인자기'
UNION ALL SELECT 'Javier Zanetti', '하비에르 사네티', 'Zanetti', '사네티'
UNION ALL SELECT 'Emilio Butragueño', '에밀리오 부트라게뇨', 'Butragueno', '부트라게뇨'
UNION ALL SELECT 'Fernando Hierro', '페르난도 이에로', 'Hierro', '이에로'
UNION ALL SELECT 'Christian Vieri', '크리스티안 비에리', 'Vieri', '비에리'
UNION ALL SELECT 'Deco', '데쿠', 'Deco', '데쿠'
UNION ALL SELECT 'Nemanja Vidić', '네마냐 비디치', 'Vidic', '비디치'
UNION ALL SELECT 'Robert Pirès', '로베르 피레스', 'Pires', '피레스'
UNION ALL SELECT 'Stefan Effenberg', '슈테판 에펜베르크', 'Effenberg', '에펜베르크'
UNION ALL SELECT 'Ashley Cole', '애슐리 콜', 'Cole', '콜'
UNION ALL SELECT 'Luis Hernández', '루이스 에르난데스', 'Hernandez', '에르난데스'
UNION ALL SELECT 'Pauleta', '파울레타', 'Pauleta', '파울레타'
UNION ALL SELECT 'Vítor Baía', '비토르 바이아', 'Baia', '바이아'
UNION ALL SELECT 'Paolo Maldini', '파올로 말디니', 'Maldini', '말디니'
UNION ALL SELECT 'Samuel Eto''o', '사뮈엘 에토', 'Etoo', '에토'
UNION ALL SELECT 'Bastian Schweinsteiger', '바스티안 슈바인슈타이거', 'Schweinsteiger', '슈바인슈타이거'
UNION ALL SELECT 'Cha Bum-kun', '차범근', 'ChaBumKun', '차범근'
UNION ALL SELECT 'Petr Čech', '페트르 체흐', 'Cech', '체흐'
UNION ALL SELECT 'Park Ji-sung', '박지성', 'ParkJiSung', '박지성'
UNION ALL SELECT 'Hristo Stoichkov', '흐리스토 스토이치코프', 'Stoichkov', '스토이치코프'
UNION ALL SELECT 'Rui Costa', '후이 코스타', 'Costa', '코스타'
UNION ALL SELECT 'Henrik Larsson', '헨릭 라르손', 'Larsson', '라르손'
UNION ALL SELECT 'Marcel Desailly', '마르셀 드사이', 'Desailly', '드사이'
UNION ALL SELECT 'Marc Overmars', '마르크 오버르마르스', 'Overmars', '오버르마르스'
UNION ALL SELECT 'Jari Litmanen', '야리 리트마넨', 'Litmanen', '리트마넨'
UNION ALL SELECT 'Juan Román Riquelme', '후안 로만 리켈메', 'Riquelme', '리켈메'
UNION ALL SELECT 'Andreas Brehme', '안드레아스 브레메', 'Brehme', '브레메'
UNION ALL SELECT 'Freddie Ljungberg', '프레디 융베리', 'Ljungberg', '융베리'
UNION ALL SELECT 'Ronaldo Nazário', '호나우두', 'Ronaldo', '호나우두'
UNION ALL SELECT 'Alessandro Nesta', '알레산드로 네스타', 'Nesta', '네스타'
UNION ALL SELECT 'Cafu', '카푸', 'Cafu', '카푸'
UNION ALL SELECT 'Iker Casillas', '이케르 카시야스', 'Casillas', '카시야스'
UNION ALL SELECT 'Wayne Rooney', '웨인 루니', 'Rooney', '루니'
UNION ALL SELECT 'Robin van Persie', '로빈 반페르시', 'VanPersie', '반페르시'
UNION ALL SELECT 'Paul Scholes', '폴 스콜스', 'Scholes', '스콜스'
UNION ALL SELECT 'Michael Ballack', '미하엘 발락', 'Ballack', '발락'
UNION ALL SELECT 'Gheorghe Hagi', '게오르게 하지', 'Hagi', '하지'
UNION ALL SELECT 'Roy Keane', '로이 킨', 'Keane', '킨'
UNION ALL SELECT 'Edwin van der Sar', '에드윈 반데르사르', 'VanDerSar', '반데르사르'
UNION ALL SELECT 'Patrick Kluivert', '파트릭 클라위버르트', 'Kluivert', '클라위버르트'
UNION ALL SELECT 'Ruud Gullit', '루드 굴리트', 'Gullit', '굴리트'
UNION ALL SELECT 'Marco van Basten', '마르코 반바스텐', 'VanBasten', '반바스텐'
UNION ALL SELECT 'George Best', '조지 베스트', 'Best', '베스트'
UNION ALL SELECT 'Andriy Shevchenko', '안드리 셰우첸코', 'Shevchenko', '셰우첸코'
UNION ALL SELECT 'Luís Figo', '루이스 피구', 'Figo', '피구'
UNION ALL SELECT 'Alan Shearer', '앨런 시어러', 'Shearer', '시어러'
UNION ALL SELECT 'Bobby Moore', '보비 무어', 'Moore', '무어'
UNION ALL SELECT 'Miroslav Klose', '미로슬라프 클로제', 'Klose', '클로제'
UNION ALL SELECT 'Ruud van Nistelrooy', '뤼트 반니스텔로이', 'VanNistelrooy', '반니스텔로이'
UNION ALL SELECT 'Ryan Giggs', '라이언 긱스', 'Giggs', '긱스'
UNION ALL SELECT 'Pelé', '펠레', 'Pele', '펠레'
UNION ALL SELECT 'Xabi Alonso', '샤비 알론소', 'Alonso', '알론소'
UNION ALL SELECT 'Gerd Müller', '게르트 뮐러', 'Muller', '뮐러'
UNION ALL SELECT 'Jairzinho', '자이르지뉴', 'Jairzinho', '자이르지뉴'
UNION ALL SELECT 'Yaya Touré', '야야 투레', 'Toure', '투레'
UNION ALL SELECT 'Franco Baresi', '프랑코 바레시', 'Baresi', '바레시'
UNION ALL SELECT 'Lothar Matthäus', '로타어 마테우스', 'Matthaus', '마테우스'
UNION ALL SELECT 'Franck Ribéry', '프랑크 리베리', 'Ribery', '리베리'
UNION ALL SELECT 'Zico', '지쿠', 'Zico', '지쿠'
UNION ALL SELECT 'Bobby Charlton', '보비 찰턴', 'Charlton', '찰턴'
UNION ALL SELECT 'Gareth Bale', '가레스 베일', 'Bale', '베일'
UNION ALL SELECT 'Lilian Thuram', '릴리앙 튀람', 'Thuram', '튀람'
UNION ALL SELECT 'Gianluigi Buffon', '잔루이지 부폰', 'Buffon', '부폰'
UNION ALL SELECT 'Franz Beckenbauer', '프란츠 베켄바워', 'Beckenbauer', '베켄바워'
UNION ALL SELECT 'Dunga', '둥가', 'Dunga', '둥가'
UNION ALL SELECT 'Diego Maradona', '디에고 마라도나', 'Maradona', '마라도나'
UNION ALL SELECT 'Andrés Iniesta', '안드레스 이니에스타', 'Iniesta', '이니에스타'
UNION ALL SELECT 'Oliver Kahn', '올리버 칸', 'Kahn', '칸'
UNION ALL SELECT 'Francesco Totti', '프란체스코 토티', 'Totti', '토티'
UNION ALL SELECT 'Zlatan Ibrahimović', '즐라탄 이브라히모비치', 'Ibrahimovic', '이브라히모비치'
UNION ALL SELECT 'Marcelo', '마르셀루', 'Marcelo', '마르셀루'
UNION ALL SELECT 'Toni Kroos', '토니 크로스', 'Kroos', '크로스'
UNION ALL SELECT 'Giorgio Chiellini', '조르조 키엘리니', 'Chiellini', '키엘리니'
UNION ALL SELECT 'Gabriel Batistuta', '가브리엘 바티스투타', 'Batistuta', '바티스투타';
