import 'package:onetouch/models/team.dart';
import 'package:onetouch/models/league.dart';
import 'package:onetouch/models/season.dart';
import 'package:onetouch/models/fixture.dart';
import 'package:onetouch/models/standing.dart';
import 'package:onetouch/models/post.dart';
import 'package:onetouch/models/user.dart';
import 'package:onetouch/models/user_profile.dart';
import 'package:onetouch/models/user_following_team.dart';

// ═══════════════════════════════════════════════════════════
// TEAMS  (teams table)
// ═══════════════════════════════════════════════════════════

const mockTeams = <Team>[
  // Premier League
  Team(
      teamId: 14,
      name: 'Manchester City',
      shortCode: 'MCI',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/14/14.png',
      primaryColor: 0xFF6CABDD),
  Team(
      teamId: 15,
      name: 'Manchester United',
      shortCode: 'MUN',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/15/15.png',
      primaryColor: 0xFFDA291C),
  Team(
      teamId: 10,
      name: 'Liverpool',
      shortCode: 'LIV',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/10/10.png',
      primaryColor: 0xFFC8102E),
  Team(
      teamId: 9,
      name: 'Arsenal',
      shortCode: 'ARS',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/9/9.png',
      primaryColor: 0xFFEF0107),
  Team(
      teamId: 5,
      name: 'Chelsea',
      shortCode: 'CHE',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/5/5.png',
      primaryColor: 0xFF034694),
  Team(
      teamId: 6,
      name: 'Tottenham Hotspur',
      shortCode: 'TOT',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/6/6.png',
      primaryColor: 0xFF132257),
  Team(
      teamId: 19,
      name: 'Newcastle United',
      shortCode: 'NEW',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/19/19.png',
      primaryColor: 0xFF241F20),
  Team(
      teamId: 7,
      name: 'Aston Villa',
      shortCode: 'AVL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/7/7.png',
      primaryColor: 0xFF670E36),

  // La Liga
  Team(
      teamId: 83,
      name: 'FC Barcelona',
      shortCode: 'FCB',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/83/83.png',
      primaryColor: 0xFFA50044),
  Team(
      teamId: 87,
      name: 'Atletico Madrid',
      shortCode: 'ATM',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/87/87.png',
      primaryColor: 0xFFCB3524),
  Team(
      teamId: 86,
      name: 'Real Madrid',
      shortCode: 'RMA',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/86/86.png',
      primaryColor: 0xFFF5C205),
  Team(
      teamId: 90,
      name: 'Sevilla FC',
      shortCode: 'SEV',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/90/90.png',
      primaryColor: 0xFFDD0000),
  Team(
      teamId: 92,
      name: 'Villarreal',
      shortCode: 'VIL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/92/92.png',
      primaryColor: 0xFFF5C205),
  Team(
      teamId: 100,
      name: 'Valencia CF',
      shortCode: 'VAL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/100/100.png',
      primaryColor: 0xFFF17E00),
  Team(
      teamId: 95,
      name: 'Athletic Bilbao',
      shortCode: 'ATH',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/95/95.png',
      primaryColor: 0xFFEE2020),
  Team(
      teamId: 89,
      name: 'Real Betis',
      shortCode: 'BET',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/89/89.png',
      primaryColor: 0xFF00954C),
  Team(
      teamId: 94,
      name: 'Real Sociedad',
      shortCode: 'RSO',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/94/94.png',
      primaryColor: 0xFF0067B1),
  Team(
      teamId: 97,
      name: 'Osasuna',
      shortCode: 'OSA',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/97/97.png',
      primaryColor: 0xFFB22222),
  Team(
      teamId: 98,
      name: 'Mallorca',
      shortCode: 'MLL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/98/98.png',
      primaryColor: 0xFFDE0000),
  Team(
      teamId: 88,
      name: 'Getafe CF',
      shortCode: 'GET',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/88/88.png',
      primaryColor: 0xFF025298),
  Team(
      teamId: 96,
      name: 'Celta Vigo',
      shortCode: 'CEL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/96/96.png',
      primaryColor: 0xFF6BABCB),
  Team(
      teamId: 728,
      name: 'Rayo Vallecano',
      shortCode: 'RAY',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/24/728.png',
      primaryColor: 0xFFE30613),
  Team(
      teamId: 546,
      name: 'Girona FC',
      shortCode: 'GIR',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/34/546.png',
      primaryColor: 0xFFCC0000),
  Team(
      teamId: 715,
      name: 'Deportivo Alaves',
      shortCode: 'ALA',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/11/715.png',
      primaryColor: 0xFF1B5296),
  Team(
      teamId: 332,
      name: 'CD Leganes',
      shortCode: 'LEG',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/12/332.png',
      primaryColor: 0xFF1B5296),
  Team(
      teamId: 91,
      name: 'Espanyol',
      shortCode: 'ESP',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/91/91.png',
      primaryColor: 0xFF0070B8),
  Team(
      teamId: 99,
      name: 'Real Valladolid',
      shortCode: 'VLL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/99/99.png',
      primaryColor: 0xFF6B2FB5),
  Team(
      teamId: 399,
      name: 'Las Palmas',
      shortCode: 'LPA',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/15/399.png',
      primaryColor: 0xFFFFCC00),

  // Serie A
  Team(
      teamId: 498,
      name: 'Inter Milan',
      shortCode: 'INT',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/242/498.png',
      primaryColor: 0xFF0E1E96),
  Team(
      teamId: 503,
      name: 'AC Milan',
      shortCode: 'MIL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/247/503.png',
      primaryColor: 0xFFCC0000),
  Team(
      teamId: 506,
      name: 'Juventus',
      shortCode: 'JUV',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/250/506.png',
      primaryColor: 0xFF2C2C2C),
  Team(
      teamId: 505,
      name: 'Napoli',
      shortCode: 'NAP',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/249/505.png',
      primaryColor: 0xFF0097A7),
  Team(
      teamId: 512,
      name: 'Lazio',
      shortCode: 'LAZ',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/0/512.png',
      primaryColor: 0xFF87CEEB),
  Team(
      teamId: 517,
      name: 'AS Roma',
      shortCode: 'ROM',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/5/517.png',
      primaryColor: 0xFFCC3300),

  // Bundesliga
  Team(
      teamId: 183,
      name: 'Bayern Munich',
      shortCode: 'BAY',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/183/183.png',
      primaryColor: 0xFFDC052D),
  Team(
      teamId: 174,
      name: 'Borussia Dortmund',
      shortCode: 'BVB',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/174/174.png',
      primaryColor: 0xFFFDE100),
  Team(
      teamId: 182,
      name: 'Bayer Leverkusen',
      shortCode: 'LEV',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/182/182.png',
      primaryColor: 0xFFE32221),
  Team(
      teamId: 185,
      name: 'RB Leipzig',
      shortCode: 'RBL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/185/185.png',
      primaryColor: 0xFFDD0741),
  Team(
      teamId: 181,
      name: 'Wolfsburg',
      shortCode: 'WOB',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/181/181.png',
      primaryColor: 0xFF65B32E),
  Team(
      teamId: 176,
      name: 'Stuttgart',
      shortCode: 'STU',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/176/176.png',
      primaryColor: 0xFFE32221),

  // Ligue 1
  Team(
      teamId: 583,
      name: 'Paris Saint-Germain',
      shortCode: 'PSG',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/71/583.png',
      primaryColor: 0xFF003087),
  Team(
      teamId: 574,
      name: 'Olympique Lyonnais',
      shortCode: 'OL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/62/574.png',
      primaryColor: 0xFFBE0000),
  Team(
      teamId: 576,
      name: 'Marseille',
      shortCode: 'OM',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/64/576.png',
      primaryColor: 0xFF2FAEE0),
  Team(
      teamId: 580,
      name: 'AS Monaco',
      shortCode: 'MON',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/68/580.png',
      primaryColor: 0xFFD4122B),
  Team(
      teamId: 578,
      name: 'OGC Nice',
      shortCode: 'NIC',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/66/578.png',
      primaryColor: 0xFFCC0000),
  Team(
      teamId: 575,
      name: 'Lille OSC',
      shortCode: 'LIL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/teams/63/575.png',
      primaryColor: 0xFF7A1222),
];

Team mockTeamById(int id) => mockTeams.firstWhere((t) => t.teamId == id);

// ═══════════════════════════════════════════════════════════
// LEAGUES  (leagues table)
// ═══════════════════════════════════════════════════════════

const mockLeagues = <League>[
  League(
      leagueId: 8,
      name: 'Premier League',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/leagues/8/8.png'),
  League(
      leagueId: 82,
      name: 'La Liga',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/leagues/82/82.png'),
  League(
      leagueId: 301,
      name: 'Serie A',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/301/301.png'),
  League(
      leagueId: 384,
      name: 'Bundesliga',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/384/384.png'),
  League(
      leagueId: 564,
      name: 'Ligue 1',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/564/564.png'),
  // ── European competitions ─────────────────────────────────
  League(
      leagueId: 2,
      name: 'UCL',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/leagues/2/2.png'),
  League(
      leagueId: 5,
      name: 'Europa League',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/leagues/5/5.png'),
  // ── Domestic cups ─────────────────────────────────────────
  League(
      leagueId: 24,
      name: 'FA Cup',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/leagues/24/24.png'),
  League(
      leagueId: 27,
      name: 'EFL Cup',
      imagePath: 'https://cdn.sportmonks.com/images/soccer/leagues/27/27.png'),
  League(
      leagueId: 570,
      name: 'Copa del Rey',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/570/570.png'),
  League(
      leagueId: 390,
      name: 'Coppa Italia',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/390/390.png'),
  League(
      leagueId: 392,
      name: 'DFB Pokal',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/392/392.png'),
  League(
      leagueId: 569,
      name: 'Coupe de France',
      imagePath:
          'https://cdn.sportmonks.com/images/soccer/leagues/569/569.png'),
];

League mockLeagueById(int id) => mockLeagues.firstWhere(
      (l) => l.leagueId == id,
      orElse: () => League(leagueId: id, name: 'Unknown'),
    );

// ═══════════════════════════════════════════════════════════
// SEASONS  (seasons table)  — 2024/25 current season per league
// ═══════════════════════════════════════════════════════════

const mockSeasons = <Season>[
  Season(
      seasonId: 23614,
      leagueId: 8,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-17 00:00:00',
      endingAt: '2025-05-25 00:00:00'),
  Season(
      seasonId: 23686,
      leagueId: 82,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-16 00:00:00',
      endingAt: '2025-05-25 00:00:00'),
  Season(
      seasonId: 23720,
      leagueId: 301,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-18 00:00:00',
      endingAt: '2025-05-25 00:00:00'),
  Season(
      seasonId: 23538,
      leagueId: 384,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-23 00:00:00',
      endingAt: '2025-05-17 00:00:00'),
  Season(
      seasonId: 23760,
      leagueId: 564,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-16 00:00:00',
      endingAt: '2025-05-25 00:00:00'),
  // ── UCL / Europa ──────────────────────────────────────────
  Season(
      seasonId: 23804,
      leagueId: 2,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-09-17 00:00:00',
      endingAt: '2025-05-31 00:00:00'),
  Season(
      seasonId: 23805,
      leagueId: 5,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-09-25 00:00:00',
      endingAt: '2025-05-21 00:00:00'),
  // ── Domestic cups ─────────────────────────────────────────
  Season(
      seasonId: 23900,
      leagueId: 24,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-11-01 00:00:00',
      endingAt: '2025-05-17 00:00:00'),
  Season(
      seasonId: 23901,
      leagueId: 27,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-13 00:00:00',
      endingAt: '2025-03-16 00:00:00'),
  Season(
      seasonId: 23902,
      leagueId: 570,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-10-29 00:00:00',
      endingAt: '2025-04-26 00:00:00'),
  Season(
      seasonId: 23903,
      leagueId: 390,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-09-24 00:00:00',
      endingAt: '2025-05-14 00:00:00'),
  Season(
      seasonId: 23904,
      leagueId: 392,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-08-16 00:00:00',
      endingAt: '2025-05-24 00:00:00'),
  Season(
      seasonId: 23905,
      leagueId: 569,
      name: '2024/25',
      isCurrent: true,
      startingAt: '2024-10-19 00:00:00',
      endingAt: '2025-05-24 00:00:00'),
];

Season mockCurrentSeason(int leagueId) =>
    mockSeasons.firstWhere((s) => s.leagueId == leagueId && s.isCurrent);

// ═══════════════════════════════════════════════════════════
// FIXTURES  (fixtures table)
// past 2 + live 1 + upcoming 2 per main team
// ═══════════════════════════════════════════════════════════

// Returns a datetime string for a live match that kicked off [minutesAgo] ago.
// Format matches SQL datetime: 'YYYY-MM-DD HH:MM:SS'
String _liveKickoff(int minutesAgo) {
  final dt = DateTime.now().toUtc().subtract(Duration(minutes: minutesAgo));
  return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')} '
      '${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}:00';
}

// Live fixtures — non-const, generated at runtime from current time.
// Each match kicked off a different number of minutes ago for variety.
final _liveManCity = Fixture(
    fixtureId: 19200003,
    seasonId: 23614,
    leagueId: 8,
    homeTeamId: 14,
    awayTeamId: 9,
    competitionType: CompetitionType.league,
    roundName: 'RO 32',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(34),
    homeScore: 1,
    awayScore: 0);
final _liveManUnited = Fixture(
    fixtureId: 19200007,
    seasonId: 23614,
    leagueId: 8,
    homeTeamId: 15,
    awayTeamId: 19,
    competitionType: CompetitionType.league,
    roundName: 'RO 32',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(61),
    homeScore: 2,
    awayScore: 1);
final _liveBarca = Fixture(
    fixtureId: 19300003,
    seasonId: 23686,
    leagueId: 82,
    homeTeamId: 83,
    awayTeamId: 90,
    competitionType: CompetitionType.league,
    roundName: 'RO 32',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(22),
    homeScore: 2,
    awayScore: 1);
final _liveAtletico = Fixture(
    fixtureId: 19300007,
    seasonId: 23686,
    leagueId: 82,
    homeTeamId: 86,
    awayTeamId: 87,
    competitionType: CompetitionType.league,
    roundName: 'RO 32',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(47),
    homeScore: 0,
    awayScore: 1);
final _liveInter = Fixture(
    fixtureId: 19400003,
    seasonId: 23720,
    leagueId: 301,
    homeTeamId: 498,
    awayTeamId: 505,
    competitionType: CompetitionType.league,
    roundName: 'RO 32',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(55),
    homeScore: 1,
    awayScore: 1);
final _liveACMilan = Fixture(
    fixtureId: 19400007,
    seasonId: 23720,
    leagueId: 301,
    homeTeamId: 503,
    awayTeamId: 506,
    competitionType: CompetitionType.league,
    roundName: 'RO 32',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(18),
    homeScore: 0,
    awayScore: 0);
final _liveBayern = Fixture(
    fixtureId: 19500003,
    seasonId: 23538,
    leagueId: 384,
    homeTeamId: 183,
    awayTeamId: 185,
    competitionType: CompetitionType.league,
    roundName: 'RO 29',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(40),
    homeScore: 2,
    awayScore: 0);
final _liveDortmund = Fixture(
    fixtureId: 19500007,
    seasonId: 23538,
    leagueId: 384,
    homeTeamId: 185,
    awayTeamId: 174,
    competitionType: CompetitionType.league,
    roundName: 'RO 29',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(40),
    homeScore: 1,
    awayScore: 2);
final _livePSG = Fixture(
    fixtureId: 19600003,
    seasonId: 23760,
    leagueId: 564,
    homeTeamId: 583,
    awayTeamId: 580,
    competitionType: CompetitionType.league,
    roundName: 'RO 30',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(29),
    homeScore: 1,
    awayScore: 0);
final _liveLyon = Fixture(
    fixtureId: 19600007,
    seasonId: 23760,
    leagueId: 564,
    homeTeamId: 576,
    awayTeamId: 574,
    competitionType: CompetitionType.league,
    roundName: 'RO 30',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(29),
    homeScore: 1,
    awayScore: 1);

// ── UCL live (Barcelona) ─────────────────────────────────────
final _liveBarcaUCL = Fixture(
    fixtureId: 20100001,
    seasonId: 23804,
    leagueId: 2,
    homeTeamId: 83,
    awayTeamId: 183,
    competitionType: CompetitionType.cup,
    roundName: 'QF',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(38),
    homeScore: 1,
    awayScore: 1);
final _liveArsenalUCL = Fixture(
    fixtureId: 20100005,
    seasonId: 23804,
    leagueId: 2,
    homeTeamId: 9,
    awayTeamId: 86,
    competitionType: CompetitionType.cup,
    roundName: 'QF',
    status: FixtureStatus.live,
    startingAt: _liveKickoff(52),
    homeScore: 2,
    awayScore: 1);

// Past & upcoming fixtures remain const.
const _pastUpcomingFixtures = <Fixture>[
  // ── Premier League (season 23614, league 8) ──────────────

  // Man City
  Fixture(
      fixtureId: 19200001,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 14,
      awayTeamId: 15,
      competitionType: CompetitionType.league,
      roundName: 'RO 20',
      status: FixtureStatus.past,
      startingAt: '2025-01-18 15:00:00',
      homeScore: 3,
      awayScore: 1),
  Fixture(
      fixtureId: 19200002,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 10,
      awayTeamId: 14,
      competitionType: CompetitionType.league,
      roundName: 'RO 25',
      status: FixtureStatus.past,
      startingAt: '2025-02-22 17:30:00',
      homeScore: 0,
      awayScore: 2),
  Fixture(
      fixtureId: 19200004,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 14,
      awayTeamId: 5,
      competitionType: CompetitionType.league,
      roundName: 'RO 33',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-12 15:00:00'),
  Fixture(
      fixtureId: 19200005,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 6,
      awayTeamId: 14,
      competitionType: CompetitionType.league,
      roundName: 'RO 34',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-19 17:30:00'),

  // Man United
  Fixture(
      fixtureId: 19200006,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 15,
      awayTeamId: 5,
      competitionType: CompetitionType.league,
      roundName: 'RO 24',
      status: FixtureStatus.past,
      startingAt: '2025-02-08 15:00:00',
      homeScore: 0,
      awayScore: 0),
  Fixture(
      fixtureId: 19200008,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 9,
      awayTeamId: 15,
      competitionType: CompetitionType.league,
      roundName: 'RO 33',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-13 14:00:00'),
  Fixture(
      fixtureId: 19200009,
      seasonId: 23614,
      leagueId: 8,
      homeTeamId: 15,
      awayTeamId: 7,
      competitionType: CompetitionType.league,
      roundName: 'RO 34',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-20 16:30:00'),

  // ── La Liga (season 23686, league 82) ────────────────────

  // Barcelona — past
  Fixture(
      fixtureId: 19300010,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 96,
      competitionType: CompetitionType.league,
      roundName: 'RO 14',
      status: FixtureStatus.past,
      startingAt: '2024-11-23 21:00:00',
      homeScore: 3,
      awayScore: 0),
  Fixture(
      fixtureId: 19300011,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 91,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 16',
      status: FixtureStatus.past,
      startingAt: '2024-12-07 21:00:00',
      homeScore: 0,
      awayScore: 2),
  Fixture(
      fixtureId: 19300012,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 88,
      competitionType: CompetitionType.league,
      roundName: 'RO 18',
      status: FixtureStatus.past,
      startingAt: '2024-12-21 21:00:00',
      homeScore: 4,
      awayScore: 0),
  Fixture(
      fixtureId: 19300013,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 399,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 20',
      status: FixtureStatus.past,
      startingAt: '2025-01-11 21:00:00',
      homeScore: 0,
      awayScore: 2),
  Fixture(
      fixtureId: 19300001,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 87,
      competitionType: CompetitionType.league,
      roundName: 'RO 22',
      status: FixtureStatus.past,
      startingAt: '2025-01-25 21:00:00',
      homeScore: 2,
      awayScore: 0),
  Fixture(
      fixtureId: 19300014,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 546,
      competitionType: CompetitionType.league,
      roundName: 'RO 24',
      status: FixtureStatus.past,
      startingAt: '2025-02-08 21:00:00',
      homeScore: 2,
      awayScore: 0),
  Fixture(
      fixtureId: 19300015,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 98,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 25',
      status: FixtureStatus.past,
      startingAt: '2025-02-15 21:00:00',
      homeScore: 1,
      awayScore: 2),
  Fixture(
      fixtureId: 19300016,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 89,
      competitionType: CompetitionType.league,
      roundName: 'RO 26',
      status: FixtureStatus.past,
      startingAt: '2025-02-22 21:00:00',
      homeScore: 3,
      awayScore: 1),
  Fixture(
      fixtureId: 19300002,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 86,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 27',
      status: FixtureStatus.past,
      startingAt: '2025-03-01 21:00:00',
      homeScore: 1,
      awayScore: 2),
  Fixture(
      fixtureId: 19300017,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 728,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 28',
      status: FixtureStatus.past,
      startingAt: '2025-03-08 21:00:00',
      homeScore: 0,
      awayScore: 1),
  Fixture(
      fixtureId: 19300018,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 97,
      competitionType: CompetitionType.league,
      roundName: 'RO 29',
      status: FixtureStatus.past,
      startingAt: '2025-03-15 21:00:00',
      homeScore: 2,
      awayScore: 0),
  Fixture(
      fixtureId: 19300019,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 95,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 30',
      status: FixtureStatus.past,
      startingAt: '2025-03-29 21:00:00',
      homeScore: 1,
      awayScore: 3),
  Fixture(
      fixtureId: 19300020,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 100,
      competitionType: CompetitionType.league,
      roundName: 'RO 31',
      status: FixtureStatus.past,
      startingAt: '2025-04-05 21:00:00',
      homeScore: 2,
      awayScore: 1),

  // Barcelona — upcoming
  Fixture(
      fixtureId: 19300004,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 92,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 33',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-13 17:00:00'),
  Fixture(
      fixtureId: 19300005,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 86,
      competitionType: CompetitionType.league,
      roundName: 'RO 34',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-20 21:00:00'),
  Fixture(
      fixtureId: 19300021,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 83,
      awayTeamId: 94,
      competitionType: CompetitionType.league,
      roundName: 'RO 35',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-27 19:00:00'),
  Fixture(
      fixtureId: 19300022,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 715,
      awayTeamId: 83,
      competitionType: CompetitionType.league,
      roundName: 'RO 36',
      status: FixtureStatus.upcoming,
      startingAt: '2025-05-04 17:00:00'),

  // Atletico Madrid
  Fixture(
      fixtureId: 19300006,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 87,
      awayTeamId: 90,
      competitionType: CompetitionType.league,
      roundName: 'RO 26',
      status: FixtureStatus.past,
      startingAt: '2025-02-22 21:00:00',
      homeScore: 3,
      awayScore: 0),
  Fixture(
      fixtureId: 19300008,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 87,
      awayTeamId: 92,
      competitionType: CompetitionType.league,
      roundName: 'RO 33',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-12 19:00:00'),
  Fixture(
      fixtureId: 19300009,
      seasonId: 23686,
      leagueId: 82,
      homeTeamId: 100,
      awayTeamId: 87,
      competitionType: CompetitionType.league,
      roundName: 'RO 34',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-19 19:00:00'),

  // ── Serie A (season 23720, league 301) ───────────────────

  // Inter Milan
  Fixture(
      fixtureId: 19400001,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 498,
      awayTeamId: 503,
      competitionType: CompetitionType.league,
      roundName: 'RO 21',
      status: FixtureStatus.past,
      startingAt: '2025-02-02 20:45:00',
      homeScore: 2,
      awayScore: 1),
  Fixture(
      fixtureId: 19400002,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 506,
      awayTeamId: 498,
      competitionType: CompetitionType.league,
      roundName: 'RO 26',
      status: FixtureStatus.past,
      startingAt: '2025-03-08 20:45:00',
      homeScore: 1,
      awayScore: 2),
  Fixture(
      fixtureId: 19400004,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 512,
      awayTeamId: 498,
      competitionType: CompetitionType.league,
      roundName: 'RO 33',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-13 20:45:00'),
  Fixture(
      fixtureId: 19400005,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 498,
      awayTeamId: 517,
      competitionType: CompetitionType.league,
      roundName: 'RO 34',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-20 20:45:00'),

  // AC Milan
  Fixture(
      fixtureId: 19400006,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 503,
      awayTeamId: 517,
      competitionType: CompetitionType.league,
      roundName: 'RO 25',
      status: FixtureStatus.past,
      startingAt: '2025-02-23 20:45:00',
      homeScore: 3,
      awayScore: 0),
  Fixture(
      fixtureId: 19400008,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 505,
      awayTeamId: 503,
      competitionType: CompetitionType.league,
      roundName: 'RO 33',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-12 20:45:00'),
  Fixture(
      fixtureId: 19400009,
      seasonId: 23720,
      leagueId: 301,
      homeTeamId: 503,
      awayTeamId: 512,
      competitionType: CompetitionType.league,
      roundName: 'RO 34',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-19 20:45:00'),

  // ── Bundesliga (season 23538, league 384) ────────────────

  // Bayern Munich
  Fixture(
      fixtureId: 19500001,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 183,
      awayTeamId: 174,
      competitionType: CompetitionType.league,
      roundName: 'RO 22',
      status: FixtureStatus.past,
      startingAt: '2025-02-01 18:30:00',
      homeScore: 3,
      awayScore: 0),
  Fixture(
      fixtureId: 19500002,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 182,
      awayTeamId: 183,
      competitionType: CompetitionType.league,
      roundName: 'RO 26',
      status: FixtureStatus.past,
      startingAt: '2025-03-01 18:30:00',
      homeScore: 1,
      awayScore: 3),
  Fixture(
      fixtureId: 19500004,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 181,
      awayTeamId: 183,
      competitionType: CompetitionType.league,
      roundName: 'RO 30',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-12 15:30:00'),
  Fixture(
      fixtureId: 19500005,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 183,
      awayTeamId: 176,
      competitionType: CompetitionType.league,
      roundName: 'RO 31',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-19 15:30:00'),

  // Borussia Dortmund
  Fixture(
      fixtureId: 19500006,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 174,
      awayTeamId: 182,
      competitionType: CompetitionType.league,
      roundName: 'RO 25',
      status: FixtureStatus.past,
      startingAt: '2025-02-22 18:30:00',
      homeScore: 2,
      awayScore: 1),
  Fixture(
      fixtureId: 19500008,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 174,
      awayTeamId: 181,
      competitionType: CompetitionType.league,
      roundName: 'RO 30',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-13 15:30:00'),
  Fixture(
      fixtureId: 19500009,
      seasonId: 23538,
      leagueId: 384,
      homeTeamId: 176,
      awayTeamId: 174,
      competitionType: CompetitionType.league,
      roundName: 'RO 31',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-20 15:30:00'),

  // ── Ligue 1 (season 23760, league 564) ───────────────────

  // PSG
  Fixture(
      fixtureId: 19600001,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 583,
      awayTeamId: 574,
      competitionType: CompetitionType.league,
      roundName: 'RO 22',
      status: FixtureStatus.past,
      startingAt: '2025-01-26 21:00:00',
      homeScore: 4,
      awayScore: 1),
  Fixture(
      fixtureId: 19600002,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 576,
      awayTeamId: 583,
      competitionType: CompetitionType.league,
      roundName: 'RO 27',
      status: FixtureStatus.past,
      startingAt: '2025-03-02 21:00:00',
      homeScore: 0,
      awayScore: 2),
  Fixture(
      fixtureId: 19600004,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 578,
      awayTeamId: 583,
      competitionType: CompetitionType.league,
      roundName: 'RO 31',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-13 21:00:00'),
  Fixture(
      fixtureId: 19600005,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 583,
      awayTeamId: 575,
      competitionType: CompetitionType.league,
      roundName: 'RO 32',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-20 21:00:00'),

  // Lyon
  Fixture(
      fixtureId: 19600006,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 574,
      awayTeamId: 578,
      competitionType: CompetitionType.league,
      roundName: 'RO 25',
      status: FixtureStatus.past,
      startingAt: '2025-02-23 19:00:00',
      homeScore: 2,
      awayScore: 0),
  Fixture(
      fixtureId: 19600008,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 574,
      awayTeamId: 580,
      competitionType: CompetitionType.league,
      roundName: 'RO 31',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-12 19:00:00'),
  Fixture(
      fixtureId: 19600009,
      seasonId: 23760,
      leagueId: 564,
      homeTeamId: 575,
      awayTeamId: 574,
      competitionType: CompetitionType.league,
      roundName: 'RO 32',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-19 19:00:00'),

  // ── UCL fixtures (Barcelona) ─────────────────────────────────
  Fixture(
      fixtureId: 20100002,
      seasonId: 23804,
      leagueId: 2,
      homeTeamId: 583,
      awayTeamId: 83,
      competitionType: CompetitionType.cup,
      roundName: 'R16',
      status: FixtureStatus.past,
      startingAt: '2025-03-11 20:00:00',
      homeScore: 1,
      awayScore: 3),
  Fixture(
      fixtureId: 20100003,
      seasonId: 23804,
      leagueId: 2,
      homeTeamId: 83,
      awayTeamId: 498,
      competitionType: CompetitionType.cup,
      roundName: 'QF',
      status: FixtureStatus.past,
      startingAt: '2025-04-01 20:00:00',
      homeScore: 2,
      awayScore: 0),
  Fixture(
      fixtureId: 20100004,
      seasonId: 23804,
      leagueId: 2,
      homeTeamId: 183,
      awayTeamId: 83,
      competitionType: CompetitionType.cup,
      roundName: 'QF',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-22 20:00:00'),

  // ── More UCL (other teams) ───────────────────────────────────
  Fixture(
      fixtureId: 20100006,
      seasonId: 23804,
      leagueId: 2,
      homeTeamId: 10,
      awayTeamId: 86,
      competitionType: CompetitionType.cup,
      roundName: 'R16',
      status: FixtureStatus.past,
      startingAt: '2025-03-04 20:00:00',
      homeScore: 1,
      awayScore: 0),
  Fixture(
      fixtureId: 20100007,
      seasonId: 23804,
      leagueId: 2,
      homeTeamId: 14,
      awayTeamId: 9,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-29 20:00:00'),
  Fixture(
      fixtureId: 20100008,
      seasonId: 23804,
      leagueId: 2,
      homeTeamId: 498,
      awayTeamId: 583,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-30 20:00:00'),

  // ── Europa League ────────────────────────────────────────────
  Fixture(
      fixtureId: 20200001,
      seasonId: 23805,
      leagueId: 5,
      homeTeamId: 15,
      awayTeamId: 517,
      competitionType: CompetitionType.cup,
      roundName: 'QF',
      status: FixtureStatus.past,
      startingAt: '2025-04-10 20:00:00',
      homeScore: 2,
      awayScore: 1),
  Fixture(
      fixtureId: 20200002,
      seasonId: 23805,
      leagueId: 5,
      homeTeamId: 6,
      awayTeamId: 574,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.upcoming,
      startingAt: '2025-05-01 20:00:00'),
  Fixture(
      fixtureId: 20200003,
      seasonId: 23805,
      leagueId: 5,
      homeTeamId: 185,
      awayTeamId: 505,
      competitionType: CompetitionType.cup,
      roundName: 'QF',
      status: FixtureStatus.past,
      startingAt: '2025-04-10 20:00:00',
      homeScore: 1,
      awayScore: 1),

  // ── FA Cup (Premier League) ──────────────────────────────────
  Fixture(
      fixtureId: 20300001,
      seasonId: 23900,
      leagueId: 24,
      homeTeamId: 14,
      awayTeamId: 6,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.past,
      startingAt: '2025-04-26 17:30:00',
      homeScore: 3,
      awayScore: 0),
  Fixture(
      fixtureId: 20300002,
      seasonId: 23900,
      leagueId: 24,
      homeTeamId: 10,
      awayTeamId: 19,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-27 16:30:00'),

  // ── EFL Cup (Carabao Cup) ────────────────────────────────────
  Fixture(
      fixtureId: 20400001,
      seasonId: 23901,
      leagueId: 27,
      homeTeamId: 10,
      awayTeamId: 9,
      competitionType: CompetitionType.cup,
      roundName: 'Final',
      status: FixtureStatus.past,
      startingAt: '2025-03-16 16:00:00',
      homeScore: 2,
      awayScore: 1),

  // ── Copa del Rey (La Liga) ───────────────────────────────────
  Fixture(
      fixtureId: 20500001,
      seasonId: 23902,
      leagueId: 570,
      homeTeamId: 86,
      awayTeamId: 87,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.past,
      startingAt: '2025-04-02 21:00:00',
      homeScore: 4,
      awayScore: 2),
  Fixture(
      fixtureId: 20500002,
      seasonId: 23902,
      leagueId: 570,
      homeTeamId: 83,
      awayTeamId: 86,
      competitionType: CompetitionType.cup,
      roundName: 'Final',
      status: FixtureStatus.upcoming,
      startingAt: '2025-04-26 22:00:00'),

  // ── Coppa Italia (Serie A) ───────────────────────────────────
  Fixture(
      fixtureId: 20600001,
      seasonId: 23903,
      leagueId: 390,
      homeTeamId: 498,
      awayTeamId: 503,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.past,
      startingAt: '2025-04-23 21:00:00',
      homeScore: 1,
      awayScore: 1),
  Fixture(
      fixtureId: 20600002,
      seasonId: 23903,
      leagueId: 390,
      homeTeamId: 506,
      awayTeamId: 512,
      competitionType: CompetitionType.cup,
      roundName: 'Final',
      status: FixtureStatus.upcoming,
      startingAt: '2025-05-14 21:00:00'),

  // ── DFB Pokal (Bundesliga) ───────────────────────────────────
  Fixture(
      fixtureId: 20700001,
      seasonId: 23904,
      leagueId: 392,
      homeTeamId: 183,
      awayTeamId: 174,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.past,
      startingAt: '2025-04-02 20:45:00',
      homeScore: 2,
      awayScore: 0),
  Fixture(
      fixtureId: 20700002,
      seasonId: 23904,
      leagueId: 392,
      homeTeamId: 185,
      awayTeamId: 182,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.past,
      startingAt: '2025-04-03 20:45:00',
      homeScore: 1,
      awayScore: 2),

  // ── Coupe de France (Ligue 1) ────────────────────────────────
  Fixture(
      fixtureId: 20800001,
      seasonId: 23905,
      leagueId: 569,
      homeTeamId: 583,
      awayTeamId: 576,
      competitionType: CompetitionType.cup,
      roundName: 'SF',
      status: FixtureStatus.past,
      startingAt: '2025-04-02 21:00:00',
      homeScore: 3,
      awayScore: 1),
  Fixture(
      fixtureId: 20800002,
      seasonId: 23905,
      leagueId: 569,
      homeTeamId: 580,
      awayTeamId: 583,
      competitionType: CompetitionType.cup,
      roundName: 'Final',
      status: FixtureStatus.upcoming,
      startingAt: '2025-05-24 21:00:00'),
];

// Combined list — evaluated lazily at first access
final mockFixtures = <Fixture>[
  ..._pastUpcomingFixtures,
  _liveManCity,
  _liveManUnited,
  _liveBarca,
  _liveAtletico,
  _liveInter,
  _liveACMilan,
  _liveBayern,
  _liveDortmund,
  _livePSG,
  _liveLyon,
  _liveBarcaUCL,
  _liveArsenalUCL,
];

List<Fixture> fixturesByTeam(int teamId) => mockFixtures
    .where((f) => f.homeTeamId == teamId || f.awayTeamId == teamId)
    .toList();

// ═══════════════════════════════════════════════════════════
// STANDINGS  (standings table)
// phase: league, group_name: '' for all (standard league phase)
// ═══════════════════════════════════════════════════════════

const mockStandings = <Standing>[
  // ── Premier League (league 8, season 23614) ──────────────
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 14,
      position: 1,
      matchesPlayed: 31,
      won: 23,
      draw: 4,
      lost: 4,
      goalsFor: 74,
      goalsAgainst: 33,
      goalDiff: 41,
      points: 73,
      last5Form: ['W', 'W', 'D', 'W', 'W']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 9,
      position: 2,
      matchesPlayed: 31,
      won: 22,
      draw: 5,
      lost: 4,
      goalsFor: 68,
      goalsAgainst: 30,
      goalDiff: 38,
      points: 71,
      last5Form: ['W', 'D', 'W', 'W', 'W']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 10,
      position: 3,
      matchesPlayed: 31,
      won: 20,
      draw: 7,
      lost: 4,
      goalsFor: 66,
      goalsAgainst: 35,
      goalDiff: 31,
      points: 67,
      last5Form: ['W', 'W', 'W', 'D', 'L']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 5,
      position: 4,
      matchesPlayed: 31,
      won: 17,
      draw: 8,
      lost: 6,
      goalsFor: 60,
      goalsAgainst: 40,
      goalDiff: 20,
      points: 59,
      last5Form: ['W', 'D', 'W', 'L', 'W']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 6,
      position: 5,
      matchesPlayed: 31,
      won: 16,
      draw: 7,
      lost: 8,
      goalsFor: 54,
      goalsAgainst: 42,
      goalDiff: 12,
      points: 55,
      last5Form: ['L', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 19,
      position: 6,
      matchesPlayed: 31,
      won: 15,
      draw: 6,
      lost: 10,
      goalsFor: 52,
      goalsAgainst: 41,
      goalDiff: 11,
      points: 51,
      last5Form: ['W', 'L', 'W', 'W', 'D']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 7,
      position: 7,
      matchesPlayed: 31,
      won: 13,
      draw: 7,
      lost: 11,
      goalsFor: 51,
      goalsAgainst: 48,
      goalDiff: 3,
      points: 46,
      last5Form: ['D', 'W', 'L', 'W', 'D']),
  Standing(
      leagueId: 8,
      seasonId: 23614,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 15,
      position: 8,
      matchesPlayed: 31,
      won: 12,
      draw: 6,
      lost: 13,
      goalsFor: 38,
      goalsAgainst: 47,
      goalDiff: -9,
      points: 42,
      last5Form: ['L', 'D', 'W', 'L', 'W']),

  // ── La Liga (league 82, season 23686) ───────────────────
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 83,
      position: 1,
      matchesPlayed: 38,
      won: 26,
      draw: 7,
      lost: 5,
      goalsFor: 79,
      goalsAgainst: 39,
      goalDiff: 40,
      points: 85,
      last5Form: ['W', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 86,
      position: 2,
      matchesPlayed: 38,
      won: 23,
      draw: 8,
      lost: 7,
      goalsFor: 82,
      goalsAgainst: 43,
      goalDiff: 39,
      points: 77,
      last5Form: ['W', 'D', 'W', 'W', 'L']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 87,
      position: 3,
      matchesPlayed: 38,
      won: 20,
      draw: 8,
      lost: 10,
      goalsFor: 62,
      goalsAgainst: 43,
      goalDiff: 19,
      points: 68,
      last5Form: ['W', 'W', 'D', 'L', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 95,
      position: 4,
      matchesPlayed: 38,
      won: 18,
      draw: 9,
      lost: 11,
      goalsFor: 55,
      goalsAgainst: 42,
      goalDiff: 13,
      points: 63,
      last5Form: ['W', 'D', 'W', 'L', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 92,
      position: 5,
      matchesPlayed: 38,
      won: 17,
      draw: 9,
      lost: 12,
      goalsFor: 64,
      goalsAgainst: 52,
      goalDiff: 12,
      points: 60,
      last5Form: ['D', 'W', 'W', 'W', 'D']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 89,
      position: 6,
      matchesPlayed: 38,
      won: 16,
      draw: 10,
      lost: 12,
      goalsFor: 58,
      goalsAgainst: 51,
      goalDiff: 7,
      points: 58,
      last5Form: ['L', 'W', 'D', 'W', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 94,
      position: 7,
      matchesPlayed: 38,
      won: 15,
      draw: 10,
      lost: 13,
      goalsFor: 51,
      goalsAgainst: 48,
      goalDiff: 3,
      points: 55,
      last5Form: ['W', 'D', 'L', 'W', 'D']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 97,
      position: 8,
      matchesPlayed: 38,
      won: 14,
      draw: 10,
      lost: 14,
      goalsFor: 46,
      goalsAgainst: 47,
      goalDiff: -1,
      points: 52,
      last5Form: ['D', 'W', 'L', 'D', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 98,
      position: 9,
      matchesPlayed: 38,
      won: 13,
      draw: 11,
      lost: 14,
      goalsFor: 42,
      goalsAgainst: 49,
      goalDiff: -7,
      points: 50,
      last5Form: ['L', 'D', 'W', 'W', 'D']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 88,
      position: 10,
      matchesPlayed: 38,
      won: 13,
      draw: 10,
      lost: 15,
      goalsFor: 36,
      goalsAgainst: 44,
      goalDiff: -8,
      points: 49,
      last5Form: ['W', 'L', 'D', 'W', 'L']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 96,
      position: 11,
      matchesPlayed: 38,
      won: 12,
      draw: 11,
      lost: 15,
      goalsFor: 52,
      goalsAgainst: 58,
      goalDiff: -6,
      points: 47,
      last5Form: ['D', 'W', 'L', 'D', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 728,
      position: 12,
      matchesPlayed: 38,
      won: 12,
      draw: 10,
      lost: 16,
      goalsFor: 47,
      goalsAgainst: 56,
      goalDiff: -9,
      points: 46,
      last5Form: ['L', 'W', 'D', 'L', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 546,
      position: 13,
      matchesPlayed: 38,
      won: 12,
      draw: 8,
      lost: 18,
      goalsFor: 49,
      goalsAgainst: 62,
      goalDiff: -13,
      points: 44,
      last5Form: ['W', 'L', 'L', 'D', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 90,
      position: 14,
      matchesPlayed: 38,
      won: 11,
      draw: 10,
      lost: 17,
      goalsFor: 43,
      goalsAgainst: 58,
      goalDiff: -15,
      points: 43,
      last5Form: ['D', 'L', 'W', 'D', 'L']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 715,
      position: 15,
      matchesPlayed: 38,
      won: 10,
      draw: 11,
      lost: 17,
      goalsFor: 38,
      goalsAgainst: 55,
      goalDiff: -17,
      points: 41,
      last5Form: ['L', 'D', 'W', 'L', 'D']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 100,
      position: 16,
      matchesPlayed: 38,
      won: 9,
      draw: 12,
      lost: 17,
      goalsFor: 40,
      goalsAgainst: 57,
      goalDiff: -17,
      points: 39,
      last5Form: ['D', 'L', 'D', 'W', 'L']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 332,
      position: 17,
      matchesPlayed: 38,
      won: 8,
      draw: 11,
      lost: 19,
      goalsFor: 31,
      goalsAgainst: 56,
      goalDiff: -25,
      points: 35,
      last5Form: ['L', 'L', 'D', 'W', 'L']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 91,
      position: 18,
      matchesPlayed: 38,
      won: 8,
      draw: 9,
      lost: 21,
      goalsFor: 36,
      goalsAgainst: 63,
      goalDiff: -27,
      points: 33,
      last5Form: ['L', 'D', 'L', 'L', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 99,
      position: 19,
      matchesPlayed: 38,
      won: 6,
      draw: 10,
      lost: 22,
      goalsFor: 30,
      goalsAgainst: 68,
      goalDiff: -38,
      points: 28,
      last5Form: ['L', 'L', 'D', 'L', 'W']),
  Standing(
      leagueId: 82,
      seasonId: 23686,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 399,
      position: 20,
      matchesPlayed: 38,
      won: 5,
      draw: 11,
      lost: 22,
      goalsFor: 28,
      goalsAgainst: 67,
      goalDiff: -39,
      points: 26,
      last5Form: ['L', 'D', 'L', 'L', 'D']),

  // ── Serie A (league 301, season 23720) ───────────────────
  Standing(
      leagueId: 301,
      seasonId: 23720,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 498,
      position: 1,
      matchesPlayed: 31,
      won: 21,
      draw: 7,
      lost: 3,
      goalsFor: 68,
      goalsAgainst: 28,
      goalDiff: 40,
      points: 70,
      last5Form: ['W', 'W', 'D', 'W', 'W']),
  Standing(
      leagueId: 301,
      seasonId: 23720,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 505,
      position: 2,
      matchesPlayed: 31,
      won: 19,
      draw: 6,
      lost: 6,
      goalsFor: 60,
      goalsAgainst: 35,
      goalDiff: 25,
      points: 63,
      last5Form: ['W', 'D', 'W', 'W', 'L']),
  Standing(
      leagueId: 301,
      seasonId: 23720,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 506,
      position: 3,
      matchesPlayed: 31,
      won: 17,
      draw: 8,
      lost: 6,
      goalsFor: 54,
      goalsAgainst: 33,
      goalDiff: 21,
      points: 59,
      last5Form: ['D', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 301,
      seasonId: 23720,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 503,
      position: 4,
      matchesPlayed: 31,
      won: 16,
      draw: 6,
      lost: 9,
      goalsFor: 55,
      goalsAgainst: 42,
      goalDiff: 13,
      points: 54,
      last5Form: ['W', 'L', 'D', 'W', 'W']),
  Standing(
      leagueId: 301,
      seasonId: 23720,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 512,
      position: 5,
      matchesPlayed: 31,
      won: 14,
      draw: 7,
      lost: 10,
      goalsFor: 50,
      goalsAgainst: 45,
      goalDiff: 5,
      points: 49,
      last5Form: ['L', 'W', 'W', 'D', 'L']),
  Standing(
      leagueId: 301,
      seasonId: 23720,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 517,
      position: 6,
      matchesPlayed: 31,
      won: 12,
      draw: 9,
      lost: 10,
      goalsFor: 45,
      goalsAgainst: 46,
      goalDiff: -1,
      points: 45,
      last5Form: ['D', 'L', 'W', 'D', 'W']),

  // ── Bundesliga (league 384, season 23538) ────────────────
  Standing(
      leagueId: 384,
      seasonId: 23538,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 183,
      position: 1,
      matchesPlayed: 29,
      won: 21,
      draw: 5,
      lost: 3,
      goalsFor: 78,
      goalsAgainst: 32,
      goalDiff: 46,
      points: 68,
      last5Form: ['W', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 384,
      seasonId: 23538,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 182,
      position: 2,
      matchesPlayed: 29,
      won: 18,
      draw: 5,
      lost: 6,
      goalsFor: 62,
      goalsAgainst: 38,
      goalDiff: 24,
      points: 59,
      last5Form: ['W', 'L', 'W', 'W', 'D']),
  Standing(
      leagueId: 384,
      seasonId: 23538,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 185,
      position: 3,
      matchesPlayed: 29,
      won: 15,
      draw: 7,
      lost: 7,
      goalsFor: 55,
      goalsAgainst: 40,
      goalDiff: 15,
      points: 52,
      last5Form: ['D', 'W', 'L', 'W', 'W']),
  Standing(
      leagueId: 384,
      seasonId: 23538,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 174,
      position: 4,
      matchesPlayed: 29,
      won: 14,
      draw: 7,
      lost: 8,
      goalsFor: 55,
      goalsAgainst: 44,
      goalDiff: 11,
      points: 49,
      last5Form: ['W', 'W', 'D', 'L', 'W']),
  Standing(
      leagueId: 384,
      seasonId: 23538,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 176,
      position: 5,
      matchesPlayed: 29,
      won: 13,
      draw: 6,
      lost: 10,
      goalsFor: 50,
      goalsAgainst: 46,
      goalDiff: 4,
      points: 45,
      last5Form: ['L', 'W', 'D', 'W', 'L']),
  Standing(
      leagueId: 384,
      seasonId: 23538,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 181,
      position: 6,
      matchesPlayed: 29,
      won: 10,
      draw: 8,
      lost: 11,
      goalsFor: 40,
      goalsAgainst: 48,
      goalDiff: -8,
      points: 38,
      last5Form: ['D', 'L', 'W', 'D', 'L']),

  // ── Ligue 1 (league 564, season 23760) ───────────────────
  Standing(
      leagueId: 564,
      seasonId: 23760,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 583,
      position: 1,
      matchesPlayed: 30,
      won: 24,
      draw: 3,
      lost: 3,
      goalsFor: 80,
      goalsAgainst: 25,
      goalDiff: 55,
      points: 75,
      last5Form: ['W', 'W', 'W', 'W', 'D']),
  Standing(
      leagueId: 564,
      seasonId: 23760,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 576,
      position: 2,
      matchesPlayed: 30,
      won: 18,
      draw: 5,
      lost: 7,
      goalsFor: 58,
      goalsAgainst: 36,
      goalDiff: 22,
      points: 59,
      last5Form: ['W', 'D', 'W', 'L', 'W']),
  Standing(
      leagueId: 564,
      seasonId: 23760,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 580,
      position: 3,
      matchesPlayed: 30,
      won: 16,
      draw: 7,
      lost: 7,
      goalsFor: 55,
      goalsAgainst: 38,
      goalDiff: 17,
      points: 55,
      last5Form: ['D', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 564,
      seasonId: 23760,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 575,
      position: 4,
      matchesPlayed: 30,
      won: 15,
      draw: 6,
      lost: 9,
      goalsFor: 48,
      goalsAgainst: 37,
      goalDiff: 11,
      points: 51,
      last5Form: ['W', 'L', 'W', 'W', 'D']),
  Standing(
      leagueId: 564,
      seasonId: 23760,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 578,
      position: 5,
      matchesPlayed: 30,
      won: 13,
      draw: 8,
      lost: 9,
      goalsFor: 44,
      goalsAgainst: 38,
      goalDiff: 6,
      points: 47,
      last5Form: ['L', 'D', 'W', 'W', 'D']),
  Standing(
      leagueId: 564,
      seasonId: 23760,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 574,
      position: 6,
      matchesPlayed: 30,
      won: 12,
      draw: 8,
      lost: 10,
      goalsFor: 47,
      goalsAgainst: 48,
      goalDiff: -1,
      points: 44,
      last5Form: ['D', 'L', 'W', 'D', 'W']),

  // ── UCL league phase (league 2, season 23804) ──────────────
  // 2024/25 새 포맷: 단일 36팀 테이블 (여기선 일부 팀만)
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 10,
      position: 1,
      matchesPlayed: 8,
      won: 7,
      draw: 0,
      lost: 1,
      goalsFor: 17,
      goalsAgainst: 5,
      goalDiff: 12,
      points: 21,
      last5Form: ['W', 'W', 'L', 'W', 'W']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 83,
      position: 2,
      matchesPlayed: 8,
      won: 6,
      draw: 1,
      lost: 1,
      goalsFor: 21,
      goalsAgainst: 9,
      goalDiff: 12,
      points: 19,
      last5Form: ['W', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 9,
      position: 3,
      matchesPlayed: 8,
      won: 6,
      draw: 1,
      lost: 1,
      goalsFor: 16,
      goalsAgainst: 3,
      goalDiff: 13,
      points: 19,
      last5Form: ['W', 'D', 'W', 'W', 'W']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 182,
      position: 4,
      matchesPlayed: 8,
      won: 5,
      draw: 2,
      lost: 1,
      goalsFor: 14,
      goalsAgainst: 6,
      goalDiff: 8,
      points: 17,
      last5Form: ['W', 'W', 'D', 'W', 'L']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 498,
      position: 5,
      matchesPlayed: 8,
      won: 5,
      draw: 2,
      lost: 1,
      goalsFor: 10,
      goalsAgainst: 3,
      goalDiff: 7,
      points: 17,
      last5Form: ['W', 'D', 'W', 'W', 'L']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 14,
      position: 6,
      matchesPlayed: 8,
      won: 5,
      draw: 1,
      lost: 2,
      goalsFor: 18,
      goalsAgainst: 11,
      goalDiff: 7,
      points: 16,
      last5Form: ['L', 'W', 'W', 'W', 'W']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 86,
      position: 7,
      matchesPlayed: 8,
      won: 5,
      draw: 0,
      lost: 3,
      goalsFor: 14,
      goalsAgainst: 10,
      goalDiff: 4,
      points: 15,
      last5Form: ['W', 'L', 'W', 'L', 'W']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 183,
      position: 8,
      matchesPlayed: 8,
      won: 5,
      draw: 0,
      lost: 3,
      goalsFor: 15,
      goalsAgainst: 9,
      goalDiff: 6,
      points: 15,
      last5Form: ['W', 'L', 'W', 'W', 'L']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 583,
      position: 9,
      matchesPlayed: 8,
      won: 4,
      draw: 1,
      lost: 3,
      goalsFor: 13,
      goalsAgainst: 9,
      goalDiff: 4,
      points: 13,
      last5Form: ['W', 'W', 'L', 'D', 'L']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 174,
      position: 10,
      matchesPlayed: 8,
      won: 4,
      draw: 1,
      lost: 3,
      goalsFor: 12,
      goalsAgainst: 10,
      goalDiff: 2,
      points: 13,
      last5Form: ['W', 'L', 'D', 'W', 'L']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 506,
      position: 11,
      matchesPlayed: 8,
      won: 3,
      draw: 3,
      lost: 2,
      goalsFor: 9,
      goalsAgainst: 8,
      goalDiff: 1,
      points: 12,
      last5Form: ['D', 'W', 'D', 'L', 'W']),
  Standing(
      leagueId: 2,
      seasonId: 23804,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 503,
      position: 12,
      matchesPlayed: 8,
      won: 3,
      draw: 2,
      lost: 3,
      goalsFor: 11,
      goalsAgainst: 10,
      goalDiff: 1,
      points: 11,
      last5Form: ['L', 'W', 'D', 'L', 'W']),

  // ── Europa League phase (league 5, season 23805) ───────────
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 15,
      position: 1,
      matchesPlayed: 8,
      won: 6,
      draw: 1,
      lost: 1,
      goalsFor: 14,
      goalsAgainst: 5,
      goalDiff: 9,
      points: 19,
      last5Form: ['W', 'W', 'D', 'W', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 6,
      position: 2,
      matchesPlayed: 8,
      won: 6,
      draw: 0,
      lost: 2,
      goalsFor: 17,
      goalsAgainst: 9,
      goalDiff: 8,
      points: 18,
      last5Form: ['W', 'L', 'W', 'W', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 185,
      position: 3,
      matchesPlayed: 8,
      won: 5,
      draw: 2,
      lost: 1,
      goalsFor: 13,
      goalsAgainst: 7,
      goalDiff: 6,
      points: 17,
      last5Form: ['W', 'D', 'W', 'W', 'D']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 517,
      position: 4,
      matchesPlayed: 8,
      won: 5,
      draw: 1,
      lost: 2,
      goalsFor: 12,
      goalsAgainst: 8,
      goalDiff: 4,
      points: 16,
      last5Form: ['W', 'L', 'W', 'D', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 505,
      position: 5,
      matchesPlayed: 8,
      won: 4,
      draw: 3,
      lost: 1,
      goalsFor: 11,
      goalsAgainst: 7,
      goalDiff: 4,
      points: 15,
      last5Form: ['D', 'W', 'W', 'D', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 576,
      position: 6,
      matchesPlayed: 8,
      won: 4,
      draw: 2,
      lost: 2,
      goalsFor: 13,
      goalsAgainst: 10,
      goalDiff: 3,
      points: 14,
      last5Form: ['W', 'W', 'L', 'D', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 19,
      position: 7,
      matchesPlayed: 8,
      won: 4,
      draw: 1,
      lost: 3,
      goalsFor: 10,
      goalsAgainst: 9,
      goalDiff: 1,
      points: 13,
      last5Form: ['L', 'W', 'D', 'W', 'L']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 90,
      position: 8,
      matchesPlayed: 8,
      won: 4,
      draw: 1,
      lost: 3,
      goalsFor: 11,
      goalsAgainst: 11,
      goalDiff: 0,
      points: 13,
      last5Form: ['W', 'L', 'W', 'L', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 89,
      position: 9,
      matchesPlayed: 8,
      won: 3,
      draw: 3,
      lost: 2,
      goalsFor: 9,
      goalsAgainst: 8,
      goalDiff: 1,
      points: 12,
      last5Form: ['D', 'W', 'D', 'W', 'L']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 94,
      position: 10,
      matchesPlayed: 8,
      won: 3,
      draw: 2,
      lost: 3,
      goalsFor: 8,
      goalsAgainst: 9,
      goalDiff: -1,
      points: 11,
      last5Form: ['W', 'L', 'D', 'D', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 512,
      position: 11,
      matchesPlayed: 8,
      won: 3,
      draw: 1,
      lost: 4,
      goalsFor: 10,
      goalsAgainst: 11,
      goalDiff: -1,
      points: 10,
      last5Form: ['L', 'W', 'L', 'D', 'W']),
  Standing(
      leagueId: 5,
      seasonId: 23805,
      phase: StandingPhase.league,
      groupName: '',
      teamId: 574,
      position: 12,
      matchesPlayed: 8,
      won: 2,
      draw: 3,
      lost: 3,
      goalsFor: 8,
      goalsAgainst: 10,
      goalDiff: -2,
      points: 9,
      last5Form: ['D', 'L', 'W', 'D', 'L']),
];

List<Standing> standingsByLeague(int leagueId) =>
    mockStandings.where((s) => s.leagueId == leagueId).toList()
      ..sort((a, b) => a.position.compareTo(b.position));

Standing? standingByTeam(int leagueId, int teamId) => mockStandings
    .where((s) => s.leagueId == leagueId && s.teamId == teamId)
    .firstOrNull;

// ═══════════════════════════════════════════════════════════════════════════
// xG STANDINGS — Big 5 leagues only (8, 82, 301, 384, 564)
// ═══════════════════════════════════════════════════════════════════════════
//
// Orderings are intentionally DIFFERENT from regular standings so the two
// views are visibly different in the UI. Real-world example: Real Madrid is
// usually 1st by points but often 2nd or 3rd by xG (they outperform their xG).
//
// W/D/L here is per-match xG comparison, not actual result.
// xPts is 1Touch rule (xG > opp ? 3 : == ? 1 : 0).

const mockXgStandings = <XgStanding>[
  // ── Premier League (league 8, season 23614) ─────────────────────────
  // Arsenal tops xG (over-creates, under-converts), Liverpool 1st in standings.
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 9,
      position: 1,
      matchesPlayed: 31,
      won: 24,
      draw: 3,
      lost: 4,
      xg: 71.2,
      xga: 25.3,
      xpts: 75.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 14,
      position: 2,
      matchesPlayed: 31,
      won: 22,
      draw: 4,
      lost: 5,
      xg: 68.0,
      xga: 30.1,
      xpts: 70.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 10,
      position: 3,
      matchesPlayed: 31,
      won: 19,
      draw: 6,
      lost: 6,
      xg: 62.5,
      xga: 35.4,
      xpts: 63.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 5,
      position: 4,
      matchesPlayed: 31,
      won: 16,
      draw: 8,
      lost: 7,
      xg: 56.8,
      xga: 41.0,
      xpts: 56.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 6,
      position: 5,
      matchesPlayed: 31,
      won: 14,
      draw: 7,
      lost: 10,
      xg: 48.3,
      xga: 43.8,
      xpts: 49.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 19,
      position: 6,
      matchesPlayed: 31,
      won: 13,
      draw: 7,
      lost: 11,
      xg: 45.7,
      xga: 46.5,
      xpts: 46.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 7,
      position: 7,
      matchesPlayed: 31,
      won: 12,
      draw: 6,
      lost: 13,
      xg: 44.2,
      xga: 49.3,
      xpts: 42.0),
  XgStanding(
      leagueId: 8,
      seasonId: 23614,
      teamId: 15,
      position: 8,
      matchesPlayed: 31,
      won: 11,
      draw: 5,
      lost: 15,
      xg: 35.1,
      xga: 51.2,
      xpts: 38.0),

  // ── La Liga (league 82, season 23686) ───────────────────────────────
  // Barcelona 1st in both, Atletico over-performs xG to grab 2nd from Real.
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 83,
      position: 1,
      matchesPlayed: 38,
      won: 27,
      draw: 6,
      lost: 5,
      xg: 84.5,
      xga: 36.1,
      xpts: 87.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 87,
      position: 2,
      matchesPlayed: 38,
      won: 22,
      draw: 8,
      lost: 8,
      xg: 70.2,
      xga: 41.4,
      xpts: 74.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 86,
      position: 3,
      matchesPlayed: 38,
      won: 21,
      draw: 9,
      lost: 8,
      xg: 68.0,
      xga: 45.7,
      xpts: 72.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 92,
      position: 4,
      matchesPlayed: 38,
      won: 18,
      draw: 8,
      lost: 12,
      xg: 55.4,
      xga: 50.2,
      xpts: 62.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 94,
      position: 5,
      matchesPlayed: 38,
      won: 16,
      draw: 9,
      lost: 13,
      xg: 51.0,
      xga: 52.8,
      xpts: 57.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 90,
      position: 6,
      matchesPlayed: 38,
      won: 14,
      draw: 8,
      lost: 16,
      xg: 48.9,
      xga: 56.0,
      xpts: 50.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 95,
      position: 7,
      matchesPlayed: 38,
      won: 13,
      draw: 9,
      lost: 16,
      xg: 45.7,
      xga: 58.4,
      xpts: 48.0),
  XgStanding(
      leagueId: 82,
      seasonId: 23686,
      teamId: 89,
      position: 8,
      matchesPlayed: 38,
      won: 12,
      draw: 8,
      lost: 18,
      xg: 42.1,
      xga: 60.5,
      xpts: 44.0),

  // ── Serie A (league 301, season 23720) ──────────────────────────────
  XgStanding(
      leagueId: 301,
      seasonId: 23720,
      teamId: 498,
      position: 1,
      matchesPlayed: 32,
      won: 23,
      draw: 5,
      lost: 4,
      xg: 65.1,
      xga: 28.5,
      xpts: 74.0),
  XgStanding(
      leagueId: 301,
      seasonId: 23720,
      teamId: 506,
      position: 2,
      matchesPlayed: 32,
      won: 20,
      draw: 7,
      lost: 5,
      xg: 58.0,
      xga: 33.2,
      xpts: 67.0),
  XgStanding(
      leagueId: 301,
      seasonId: 23720,
      teamId: 505,
      position: 3,
      matchesPlayed: 32,
      won: 18,
      draw: 8,
      lost: 6,
      xg: 52.7,
      xga: 36.0,
      xpts: 62.0),
  XgStanding(
      leagueId: 301,
      seasonId: 23720,
      teamId: 503,
      position: 4,
      matchesPlayed: 32,
      won: 16,
      draw: 7,
      lost: 9,
      xg: 48.3,
      xga: 39.4,
      xpts: 55.0),
  XgStanding(
      leagueId: 301,
      seasonId: 23720,
      teamId: 517,
      position: 5,
      matchesPlayed: 32,
      won: 15,
      draw: 7,
      lost: 10,
      xg: 45.1,
      xga: 41.6,
      xpts: 52.0),
  XgStanding(
      leagueId: 301,
      seasonId: 23720,
      teamId: 512,
      position: 6,
      matchesPlayed: 32,
      won: 14,
      draw: 7,
      lost: 11,
      xg: 42.5,
      xga: 44.0,
      xpts: 49.0),

  // ── Bundesliga (league 384, season 23538) ───────────────────────────
  XgStanding(
      leagueId: 384,
      seasonId: 23538,
      teamId: 183,
      position: 1,
      matchesPlayed: 29,
      won: 22,
      draw: 4,
      lost: 3,
      xg: 70.4,
      xga: 24.1,
      xpts: 70.0),
  XgStanding(
      leagueId: 384,
      seasonId: 23538,
      teamId: 185,
      position: 2,
      matchesPlayed: 29,
      won: 18,
      draw: 6,
      lost: 5,
      xg: 58.0,
      xga: 30.8,
      xpts: 60.0),
  XgStanding(
      leagueId: 384,
      seasonId: 23538,
      teamId: 174,
      position: 3,
      matchesPlayed: 29,
      won: 16,
      draw: 7,
      lost: 6,
      xg: 52.6,
      xga: 35.1,
      xpts: 55.0),
  XgStanding(
      leagueId: 384,
      seasonId: 23538,
      teamId: 182,
      position: 4,
      matchesPlayed: 29,
      won: 14,
      draw: 6,
      lost: 9,
      xg: 46.8,
      xga: 40.3,
      xpts: 48.0),
  XgStanding(
      leagueId: 384,
      seasonId: 23538,
      teamId: 176,
      position: 5,
      matchesPlayed: 29,
      won: 12,
      draw: 7,
      lost: 10,
      xg: 41.2,
      xga: 43.7,
      xpts: 43.0),
  XgStanding(
      leagueId: 384,
      seasonId: 23538,
      teamId: 181,
      position: 6,
      matchesPlayed: 29,
      won: 11,
      draw: 6,
      lost: 12,
      xg: 38.5,
      xga: 46.2,
      xpts: 39.0),

  // ── Ligue 1 (league 564, season 23760) ──────────────────────────────
  XgStanding(
      leagueId: 564,
      seasonId: 23760,
      teamId: 583,
      position: 1,
      matchesPlayed: 30,
      won: 23,
      draw: 5,
      lost: 2,
      xg: 68.2,
      xga: 22.4,
      xpts: 74.0),
  XgStanding(
      leagueId: 564,
      seasonId: 23760,
      teamId: 580,
      position: 2,
      matchesPlayed: 30,
      won: 17,
      draw: 6,
      lost: 7,
      xg: 51.7,
      xga: 33.0,
      xpts: 57.0),
  XgStanding(
      leagueId: 564,
      seasonId: 23760,
      teamId: 576,
      position: 3,
      matchesPlayed: 30,
      won: 15,
      draw: 8,
      lost: 7,
      xg: 47.2,
      xga: 36.8,
      xpts: 53.0),
  XgStanding(
      leagueId: 564,
      seasonId: 23760,
      teamId: 575,
      position: 4,
      matchesPlayed: 30,
      won: 13,
      draw: 8,
      lost: 9,
      xg: 41.0,
      xga: 39.1,
      xpts: 47.0),
  XgStanding(
      leagueId: 564,
      seasonId: 23760,
      teamId: 574,
      position: 5,
      matchesPlayed: 30,
      won: 12,
      draw: 7,
      lost: 11,
      xg: 38.5,
      xga: 43.7,
      xpts: 43.0),
  XgStanding(
      leagueId: 564,
      seasonId: 23760,
      teamId: 578,
      position: 6,
      matchesPlayed: 30,
      won: 11,
      draw: 8,
      lost: 11,
      xg: 36.0,
      xga: 45.2,
      xpts: 41.0),
];

List<XgStanding> xgStandingsByLeague(int leagueId) =>
    mockXgStandings.where((x) => x.leagueId == leagueId).toList()
      ..sort((a, b) => a.position.compareTo(b.position));

XgStanding? xgStandingByTeam(int leagueId, int teamId) => mockXgStandings
    .where((x) => x.leagueId == leagueId && x.teamId == teamId)
    .firstOrNull;

// ═══════════════════════════════════════════════════════════════════════════
// TEAM ATTRIBUTE SCORES — for the radar chart on Analysis tab
// ═══════════════════════════════════════════════════════════════════════════
//
// Backend mapping (from team_attribute_group_scores table, Big 5 only):
//   attack       ← finishing.display_score_0_100
//   progression  ← attacking_threat.display_score_0_100
//   dominance    ← chance_creation.display_score_0_100
//   defense      ← defending.display_score_0_100
//   possession   ← possession_build_up.display_score_0_100
//   pressure     ← composite from raw feature:
//                  clamp(50 + 15 * z(-dangerous_attacks_against_per_match), 5, 95)
//                  i.e. lower dangerous_attacks_against = higher pressure score.
//                  This is conceptually distinct from `defending`, which is
//                  about resisting shots/goals once they occur. Pressure
//                  measures preventing the opponent from creating chances
//                  in the first place.
//
// Display range: 5-95 (per loader's clamp).
// seasonLabel is denormalized here for picker convenience; real API would
// join with the seasons table.

class TeamAttributeScores {
  final int teamId;
  final int seasonId;
  final String seasonLabel; // e.g. "24/25", "22/23"
  final double attack;
  final double progression;
  final double pressure;
  final double dominance;
  final double defense;
  final double possession;

  const TeamAttributeScores({
    required this.teamId,
    required this.seasonId,
    required this.seasonLabel,
    required this.attack,
    required this.progression,
    required this.pressure,
    required this.dominance,
    required this.defense,
    required this.possession,
  });

  // Convenience for the radar chart — order matches matchpreview's getTitle().
  List<double> get radarValues => [
        attack,
        progression,
        pressure,
        dominance,
        defense,
        possession,
      ];
}

// Axis labels in the same order as TeamAttributeScores.radarValues.
const teamAttributeLabels = <String>[
  'Attack',
  'Progression',
  'Pressure',
  'Dominance',
  'Defense',
  'Possession',
];

const mockTeamAttributes = <TeamAttributeScores>[
  // ── FC Barcelona ─────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 83,
      seasonId: 23686,
      seasonLabel: '24/25',
      attack: 92,
      progression: 85,
      pressure: 78,
      dominance: 88,
      defense: 75,
      possession: 94),
  TeamAttributeScores(
      teamId: 83,
      seasonId: 21795,
      seasonLabel: '22/23',
      attack: 82,
      progression: 78,
      pressure: 70,
      dominance: 80,
      defense: 82,
      possession: 89),
  TeamAttributeScores(
      teamId: 83,
      seasonId: 19744,
      seasonLabel: '21/22',
      attack: 75,
      progression: 72,
      pressure: 65,
      dominance: 75,
      defense: 78,
      possession: 86),
  TeamAttributeScores(
      teamId: 83,
      seasonId: 18444,
      seasonLabel: '20/21',
      attack: 72,
      progression: 70,
      pressure: 62,
      dominance: 73,
      defense: 75,
      possession: 88),

  // ── Real Madrid ──────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 86,
      seasonId: 23686,
      seasonLabel: '24/25',
      attack: 88,
      progression: 82,
      pressure: 75,
      dominance: 84,
      defense: 82,
      possession: 80),
  TeamAttributeScores(
      teamId: 86,
      seasonId: 21795,
      seasonLabel: '22/23',
      attack: 85,
      progression: 80,
      pressure: 73,
      dominance: 82,
      defense: 85,
      possession: 78),
  TeamAttributeScores(
      teamId: 86,
      seasonId: 19744,
      seasonLabel: '21/22',
      attack: 90,
      progression: 78,
      pressure: 70,
      dominance: 85,
      defense: 80,
      possession: 75),

  // ── Liverpool ────────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 10,
      seasonId: 23614,
      seasonLabel: '24/25',
      attack: 90,
      progression: 84,
      pressure: 80,
      dominance: 86,
      defense: 78,
      possession: 78),
  TeamAttributeScores(
      teamId: 10,
      seasonId: 21646,
      seasonLabel: '22/23',
      attack: 84,
      progression: 80,
      pressure: 82,
      dominance: 80,
      defense: 75,
      possession: 76),

  // ── Arsenal ──────────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 9,
      seasonId: 23614,
      seasonLabel: '24/25',
      attack: 87,
      progression: 85,
      pressure: 82,
      dominance: 83,
      defense: 85,
      possession: 81),
  TeamAttributeScores(
      teamId: 9,
      seasonId: 21646,
      seasonLabel: '22/23',
      attack: 80,
      progression: 78,
      pressure: 78,
      dominance: 78,
      defense: 80,
      possession: 76),

  // ── Manchester City ──────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 14,
      seasonId: 23614,
      seasonLabel: '24/25',
      attack: 88,
      progression: 86,
      pressure: 84,
      dominance: 87,
      defense: 80,
      possession: 92),
  TeamAttributeScores(
      teamId: 14,
      seasonId: 21646,
      seasonLabel: '22/23',
      attack: 92,
      progression: 88,
      pressure: 86,
      dominance: 90,
      defense: 84,
      possession: 94),

  // ── Bayern Munich ────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 183,
      seasonId: 23538,
      seasonLabel: '24/25',
      attack: 90,
      progression: 84,
      pressure: 82,
      dominance: 85,
      defense: 78,
      possession: 86),

  // ── PSG ──────────────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 583,
      seasonId: 23760,
      seasonLabel: '24/25',
      attack: 88,
      progression: 82,
      pressure: 75,
      dominance: 86,
      defense: 76,
      possession: 84),

  // ── Inter Milan ──────────────────────────────────────────────────
  TeamAttributeScores(
      teamId: 498,
      seasonId: 23720,
      seasonLabel: '24/25',
      attack: 86,
      progression: 80,
      pressure: 78,
      dominance: 82,
      defense: 84,
      possession: 80),
];

TeamAttributeScores? teamAttributesByTeamSeason(int teamId, int seasonId) =>
    mockTeamAttributes
        .where((a) => a.teamId == teamId && a.seasonId == seasonId)
        .firstOrNull;

// All seasons recorded for a team, newest first.
List<TeamAttributeScores> teamAttributesByTeam(int teamId) {
  final list = mockTeamAttributes.where((a) => a.teamId == teamId).toList();
  list.sort((a, b) => b.seasonId.compareTo(a.seasonId));
  return list;
}

// ═══════════════════════════════════════════════════════════
// POSTS  (posts table)
// ═══════════════════════════════════════════════════════════

const mockPosts = <Post>[
  Post(
      postId: 1,
      userId: 1001,
      category: PostCategory.news,
      title: 'Barcelona clinch La Liga title with five games to spare',
      body:
          'FC Barcelona secured their 28th La Liga title on Tuesday night after a commanding 4-1 victory over Sevilla at the Estadio Olimpic. Lewandowski scored a hat-trick as the Catalans ran riot in the second half.',
      mediaUrl: 'https://picsum.photos/200',
      createdAt: '2025-04-07 21:30:00',
      updatedAt: '2025-04-07 21:30:00'),
  Post(
      postId: 2,
      userId: 1002,
      category: PostCategory.analysis,
      title: 'Why Bayern\'s pressing system is breaking records this season',
      body:
          'Harry Kane has been the fulcrum of Bayern Munich\'s record-breaking Bundesliga campaign. In this analysis we break down the numbers behind their 78-goal tally through 29 matchdays and how Kompany\'s high press has revolutionised their build-up play.',
      createdAt: '2025-04-06 14:00:00',
      updatedAt: '2025-04-06 14:00:00'),
  Post(
      postId: 3,
      userId: 1001,
      category: PostCategory.general,
      title: 'Best XI of the week — RO 32',
      body:
          'Our community picks the standout performers from across all five major European leagues this weekend. Inter Milan\'s goalkeeper makes the cut after his stunning save denied Napoli a late equaliser.',
      createdAt: '2025-04-05 10:00:00',
      updatedAt: '2025-04-05 10:00:00'),
  Post(
      postId: 4,
      userId: 1003,
      category: PostCategory.news,
      title: 'Man City confirm Haaland fit for Arsenal clash',
      body:
          'Pep Guardiola confirmed in his pre-match press conference that Erling Haaland has fully recovered from the hamstring issue that kept him out of last weekend\'s draw at Villa Park. The Norwegian is expected to lead the line tonight.',
      createdAt: '2025-04-08 11:00:00',
      updatedAt: '2025-04-08 11:00:00'),
  Post(
      postId: 5,
      userId: 1002,
      category: PostCategory.analysis,
      title: 'Atletico\'s defensive structure under the microscope',
      body:
          'Simeone\'s side have conceded just 35 goals in 31 league games — only Barcelona and Real Madrid have better records. We examine the 4-4-2 mid-block that has frustrated Europe\'s top attacks all season.',
      createdAt: '2025-04-04 09:00:00',
      updatedAt: '2025-04-04 09:00:00'),
];

// ═══════════════════════════════════════════════════════════
// USERS  (users table)
// ═══════════════════════════════════════════════════════════

const mockUsers = <User>[
  User(
      userId: 1001,
      displayName: 'Alex Kim',
      username: 'alexkim',
      email: 'alexkim@gmail.com',
      avatarAsset: 'assets/profileavatar.png',
      createdAt: '2024-08-15 09:00:00'), // Barcelona fan
  User(
      userId: 1002,
      displayName: 'Maria Schmidt',
      username: 'mariaschmidt',
      email: 'maria.schmidt@web.de',
      avatarAsset: 'assets/profileavatar.png',
      createdAt: '2024-09-01 12:30:00'), // Bayern fan
  User(
      userId: 1003,
      displayName: 'James Walker',
      username: 'jwalker',
      email: 'jwalker@outlook.com',
      avatarAsset: 'assets/profileavatar.png',
      createdAt: '2024-10-20 18:45:00'), // Man City fan
  User(
      userId: 1004,
      displayName: 'Sophie Martin',
      username: 'sophiem',
      email: 'sophie.martin@laposte.fr',
      avatarAsset: 'assets/profileavatar.png',
      createdAt: '2025-01-05 11:00:00'), // PSG fan
  User(
      userId: 1005,
      displayName: 'Lucas Santos',
      username: 'lsantos',
      email: 'lucas.santos@bol.com.br',
      avatarAsset: 'assets/profileavatar.png',
      createdAt: '2025-02-14 08:00:00'), // Liverpool fan
];

User mockUserById(int id) =>
    mockUsers.firstWhere((u) => u.userId == id, orElse: () => mockUsers.first);

// ═══════════════════════════════════════════════════════════
// USER PROFILES  (user_profiles table)
// ═══════════════════════════════════════════════════════════

const mockUserProfiles = <UserProfile>[
  UserProfile(
      userId: 1001,
      favoriteTeamId: 83,
      pts: 1420,
      postCount: 8,
      commentCount: 54,
      createdAt: '2024-08-15 09:01:00',
      updatedAt: '2025-04-07 21:30:00'), // Barcelona
  UserProfile(
      userId: 1002,
      favoriteTeamId: 183,
      pts: 870,
      postCount: 5,
      commentCount: 31,
      createdAt: '2024-09-01 12:31:00',
      updatedAt: '2025-04-06 14:00:00'), // Bayern
  UserProfile(
      userId: 1003,
      favoriteTeamId: 14,
      pts: 310,
      postCount: 2,
      commentCount: 12,
      createdAt: '2024-10-20 18:46:00',
      updatedAt: '2025-04-08 11:00:00'), // Man City
  UserProfile(
      userId: 1004,
      favoriteTeamId: 583,
      pts: 2250,
      postCount: 19,
      commentCount: 88,
      createdAt: '2025-01-05 11:01:00',
      updatedAt: '2025-04-05 10:00:00'), // PSG
  UserProfile(
      userId: 1005,
      favoriteTeamId: 10,
      pts: 540,
      postCount: 3,
      commentCount: 27,
      createdAt: '2025-02-14 08:01:00',
      updatedAt: '2025-04-04 09:00:00'), // Liverpool
];

UserProfile mockUserProfileById(int id) => mockUserProfiles
    .firstWhere((p) => p.userId == id, orElse: () => mockUserProfiles.first);

// ═══════════════════════════════════════════════════════════
// USER FOLLOWING TEAMS  (user_following_teams table)
// ═══════════════════════════════════════════════════════════

const mockUserFollowingTeams = <UserFollowingTeam>[
  // 1001 Alex Kim: Barcelona + Bayern
  UserFollowingTeam(userId: 1001, teamId: 83, createdAt: '2024-08-15 09:01:00'),
  UserFollowingTeam(
      userId: 1001, teamId: 183, createdAt: '2024-08-15 09:02:00'),
  // 1002 Maria Schmidt: Bayern + Dortmund
  UserFollowingTeam(
      userId: 1002, teamId: 183, createdAt: '2024-09-01 12:31:00'),
  UserFollowingTeam(
      userId: 1002, teamId: 174, createdAt: '2024-09-01 12:32:00'),
  // 1003 James Walker: Man City + Inter Milan
  UserFollowingTeam(userId: 1003, teamId: 14, createdAt: '2024-10-20 18:46:00'),
  UserFollowingTeam(
      userId: 1003, teamId: 498, createdAt: '2024-10-20 18:47:00'),
  // 1004 Sophie Martin: PSG + Marseille
  UserFollowingTeam(
      userId: 1004, teamId: 583, createdAt: '2025-01-05 11:01:00'),
  UserFollowingTeam(
      userId: 1004, teamId: 576, createdAt: '2025-01-05 11:02:00'),
  // 1005 Lucas Santos: Liverpool + Arsenal
  UserFollowingTeam(userId: 1005, teamId: 10, createdAt: '2025-02-14 08:01:00'),
  UserFollowingTeam(userId: 1005, teamId: 9, createdAt: '2025-02-14 08:02:00'),
];

List<int> followingTeamIds(int userId) => mockUserFollowingTeams
    .where((f) => f.userId == userId)
    .map((f) => f.teamId)
    .toList();

// ═══════════════════════════════════════════════════════════
// USER FOLLOWING PLAYERS
// SQL table (not yet in live schema): user_following_players
// user_id | player_id | player_name | jersey_number | team_name | image_url
// ═══════════════════════════════════════════════════════════

class MockFollowingPlayer {
  final int userId;
  final int playerId;
  final String playerName;
  final int jerseyNumber;
  final String teamName;
  final String? imageUrl;

  const MockFollowingPlayer({
    required this.userId,
    required this.playerId,
    required this.playerName,
    required this.jerseyNumber,
    required this.teamName,
    this.imageUrl,
  });
}

const mockUserFollowingPlayers = <MockFollowingPlayer>[
  // 1001 Alex Kim — Barcelona players
  MockFollowingPlayer(
      userId: 1001,
      playerId: 801,
      playerName: 'R. Lewandowski',
      jerseyNumber: 9,
      teamName: 'FC Barcelona'),
  MockFollowingPlayer(
      userId: 1001,
      playerId: 802,
      playerName: 'L. Yamal',
      jerseyNumber: 27,
      teamName: 'FC Barcelona'),
  MockFollowingPlayer(
      userId: 1001,
      playerId: 803,
      playerName: 'Pedri',
      jerseyNumber: 8,
      teamName: 'FC Barcelona'),
  MockFollowingPlayer(
      userId: 1001,
      playerId: 804,
      playerName: 'R. Araújo',
      jerseyNumber: 4,
      teamName: 'FC Barcelona'),
  // 1002 Maria Schmidt — Bayern players
  MockFollowingPlayer(
      userId: 1002,
      playerId: 811,
      playerName: 'H. Kane',
      jerseyNumber: 9,
      teamName: 'Bayern Munich'),
  MockFollowingPlayer(
      userId: 1002,
      playerId: 812,
      playerName: 'J. Musiala',
      jerseyNumber: 42,
      teamName: 'Bayern Munich'),
  MockFollowingPlayer(
      userId: 1002,
      playerId: 813,
      playerName: 'L. Sané',
      jerseyNumber: 10,
      teamName: 'Bayern Munich'),
  // 1003 James Walker — Man City players
  MockFollowingPlayer(
      userId: 1003,
      playerId: 821,
      playerName: 'E. Haaland',
      jerseyNumber: 9,
      teamName: 'Manchester City'),
  MockFollowingPlayer(
      userId: 1003,
      playerId: 822,
      playerName: 'K. De Bruyne',
      jerseyNumber: 17,
      teamName: 'Manchester City'),
  MockFollowingPlayer(
      userId: 1003,
      playerId: 823,
      playerName: 'B. Silva',
      jerseyNumber: 20,
      teamName: 'Manchester City'),
  MockFollowingPlayer(
      userId: 1003,
      playerId: 824,
      playerName: 'J. Gvardiol',
      jerseyNumber: 24,
      teamName: 'Manchester City'),
  // 1004 Sophie Martin — PSG players
  MockFollowingPlayer(
      userId: 1004,
      playerId: 831,
      playerName: 'O. Dembélé',
      jerseyNumber: 10,
      teamName: 'Paris Saint-Germain'),
  MockFollowingPlayer(
      userId: 1004,
      playerId: 832,
      playerName: 'A. Hakimi',
      jerseyNumber: 2,
      teamName: 'Paris Saint-Germain'),
  MockFollowingPlayer(
      userId: 1004,
      playerId: 833,
      playerName: 'Vitinha',
      jerseyNumber: 17,
      teamName: 'Paris Saint-Germain'),
  // 1005 Lucas Santos — Liverpool players
  MockFollowingPlayer(
      userId: 1005,
      playerId: 841,
      playerName: 'M. Salah',
      jerseyNumber: 11,
      teamName: 'Liverpool'),
  MockFollowingPlayer(
      userId: 1005,
      playerId: 842,
      playerName: 'V. van Dijk',
      jerseyNumber: 4,
      teamName: 'Liverpool'),
  MockFollowingPlayer(
      userId: 1005,
      playerId: 843,
      playerName: 'Alisson',
      jerseyNumber: 1,
      teamName: 'Liverpool'),
];

List<MockFollowingPlayer> followingPlayersByUser(int userId) =>
    mockUserFollowingPlayers.where((p) => p.userId == userId).toList();

// ═══════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════

// Returns "LEAGUE · Nth" for a team's primary domestic league standing.
String teamLeagueLabel(int teamId) {
  const domesticIds = {8, 82, 301, 384, 564};
  final s = mockStandings
      .where((s) => s.teamId == teamId && domesticIds.contains(s.leagueId))
      .firstOrNull;
  if (s == null) return '';
  final league = mockLeagueById(s.leagueId);
  final pos = s.position;
  final suffix = pos == 1
      ? '1st'
      : pos == 2
          ? '2nd'
          : pos == 3
              ? '3rd'
              : '${pos}th';
  return '${league.name} $suffix';
}
